# Generated by Django 3.2.15 on 2022-08-17 00:02

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('uuid', models.SlugField(primary_key=True, serialize=False)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('nickname', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('statename', localflavor.us.models.USStateField(max_length=2)),
                ('name_last', models.CharField(max_length=127)),
                ('name_first', models.CharField(max_length=127)),
                ('name_middle', models.CharField(blank=True, max_length=127)),
                ('cell_phone_1', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, region=None)),
                ('cell_phone_2', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, region=None)),
                ('land_phone_1', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, region=None)),
                ('land_phone_2', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, region=None)),
                ('notes', models.TextField(blank=True)),
                ('priority', models.SmallIntegerField(db_index=True, default=0)),
                ('provided_at', models.DateTimeField(blank=True, null=True)),
                ('provided_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phonebank.agent')),
            ],
        ),
        migrations.CreateModel(
            name='TelnyxCredential',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, max_length=1023)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phonebank.agent')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phonebank.room'),
        ),
    ]
