# Generated by Django 4.2.20 on 2025-03-07 01:44

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ("phonebank", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="voter",
            old_name="name_first",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="voter",
            old_name="name_last",
            new_name="last_name",
        ),
        migrations.RenameField(
            model_name="voter",
            old_name="name_middle",
            new_name="middle_name",
        ),
        migrations.RenameField(
            model_name="voter",
            old_name="statename",
            new_name="state",
        ),
        migrations.AlterField(
            model_name="voter",
            name="state",
            field=localflavor.us.models.USStateField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="voter",
            name="address",
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name="voter",
            name="city",
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name="voter",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="voter",
            name="zip_code",
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10),
        ),
    ]
